#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=8GB
#SBATCH --time=10:00:00
#SBATCH -p agsmall
#SBATCH -o genome_harmonizer_%a.out
#SBATCH -e genome_harmonizer_%a.err
#SBATCH --job-name genome_harmonizer

module load java/openjdk-17.0.2
module load plink

REF=/home/gdc/shared/GDC_pipeline/Ref
WORK=$1
NAME=$2
CHR=$SLURM_ARRAY_TASK_ID

java -Xmx8g -jar $REF/GenotypeHarmonizer/GenotypeHarmonizer.jar --input $WORK/lifted/study.$NAME.lifted.chr${CHR} --inputType PLINK_BED --ref $REF/1000G_highcoverage/1kGP_high_coverage_Illumina.ALL.filtered.SNV_INDEL_SV_phased_panel --refType VCF --keep --output $WORK/aligned/study.$NAME.lifted.chr${CHR}.aligned

